name: erp_modular
description: Sistema ERP modular con IA integrada

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  fl_chart: ^0.69.2
  flutter_dotenv: ^5.2.1
  table_calendar: ^3.1.3

  # Iconos
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^7.0.7296

  shared_preferences: ^2.3.5

  # Mapas
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  latlong2: ^0.9.1
  
  # Gestión de Estado
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  
  # Backend y API
  dio: ^5.7.0
  dio_http2_adapter: ^2.5.3
  supabase_flutter: ^2.8.1
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  firebase_analytics: ^11.3.6
  firebase_messaging: ^15.1.6
  
  # UI/UX
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  lottie: ^3.1.3
  
  # Utilidades
  intl: ^0.19.0
  logger: ^2.5.0
  uuid: ^4.5.1

flutter:
  # Asegúrate que esta sección exista para los assets
  assets:
    - assets/fonts/
    - assets/images/
    - assets/.env

  uses-material-design: true
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
          

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13